import type { Metadata } from "next";
import { Almendra, Inter, Jersey_15, Orbitron, Pirata_One } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter({
  variable: "--font-inter"
})

const orbitron = Orbitron({
  variable: "--font-orbitron"
})

const legend = Almendra({
  variable: "--font-legend",
  weight: "400"
})

export const metadata: Metadata = {
  title: "IPL Auction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${orbitron.variable} ${legend.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
